AllCops:
  # NewCops: enable
  TargetRubyVersion: 3.0.3
  RubyInterpreters:
    - ruby
  Exclude:
    - 'bin/*'
    - 'config.ru'
    - 'config/**/**'
    - 'config/**'
    - 'lib/*'
    - 'db/*'
    - 'db/**/*'
    - 'test/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'Rakefile'
Style/RedundantEach:
  Enabled: true
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'class_methods']
Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'Gemfile'
Style/Encoding:
  Enabled: false
Gemspec/DeprecatedAttributeAssignment:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false
Layout/LineContinuationLeadingSpace:
  Enabled: false
Layout/LineContinuationSpacing:
  Enabled: false
Layout/LineEndStringConcatenationIndentation:
  Enabled: false
Layout/SpaceBeforeBrackets:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Lint/DuplicateMagicComment:
  Enabled: true
Lint/AmbiguousAssignment:
  Enabled: false
Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Lint/AmbiguousRange:
  Enabled: false
Lint/ConstantOverwrittenInRescue:
  Enabled: false
Lint/DeprecatedConstants:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: false
Lint/EmptyBlock:
  Enabled: false
Lint/EmptyClass:
  Enabled: false
Lint/EmptyInPattern:
  Enabled: false
Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: false
Lint/LambdaWithoutLiteralBlock:
  Enabled: false
Lint/NoReturnInBeginEndBlocks:
  Enabled: false
Lint/NonAtomicFileOperation:
  Enabled: false
Lint/NumberedParameterAssignment:
  Enabled: false
Lint/OrAssignmentToConstant:
  Enabled: false
Lint/RedundantDirGlobSort:
  Enabled: false
Lint/RefinementImportMethods:
  Enabled: false
Lint/RequireRangeParentheses:
  Enabled: false
Lint/RequireRelativeSelfPath:
  Enabled: false
Lint/SymbolConversion:
  Enabled: false
Lint/ToEnumArguments:
  Enabled: false
Lint/TripleQuotes:
  Enabled: false
Lint/UnexpectedBlockArity:
  Enabled: false
Lint/UnmodifiedReduceAccumulator:
  Enabled: false
Lint/UselessRuby2Keywords:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Style/Documentation:
  Enabled: false
Security/CompoundHash:
  Enabled: false
Security/IoMethods:
  Enabled: false
Style/ArgumentsForwarding:
  Enabled: false
Style/CollectionCompact:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/EmptyHeredoc:
  Enabled: false
Style/EndlessMethod:
  Enabled: false
Style/EnvHome:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
Style/FileRead:
  Enabled: false
Style/FileWrite:
  Enabled: false
Style/HashConversion:
  Enabled: false
Style/HashExcept:
  Enabled: false
Style/IfWithBooleanLiteralBranches:
  Enabled: false
Style/InPatternThen:
  Enabled: false
Style/MagicCommentFormat:
  Enabled: false
Style/MapCompactWithConditionalBlock:
  Enabled: false
Style/MapToHash:
  Enabled: false
Style/MultilineInPatternThen:
  Enabled: false
Style/NegatedIfElseCondition:
  Enabled: false
Style/NestedFileDirname:
  Enabled: false
Style/NilLambda:
  Enabled: false
Style/NumberedParameters:
  Enabled: false
Style/NumberedParametersLimit:
  Enabled: false
Style/ObjectThen:
  Enabled: false
Style/OpenStructUse:
  Enabled: false
Style/QuotedSymbols:
  Enabled: false
Style/RedundantArgument:
  Enabled: false
Style/RedundantInitialize:
  Enabled: false
Style/RedundantSelfAssignmentBranch:
  Enabled: false
Style/SelectByRegexp:
  Enabled: false
Style/StringChars:
  Enabled: false
Style/SwapValues:
  Enabled: false
Style/OperatorMethodCall:
  Enabled: true
Style/RedundantStringEscape:
  Enabled: true
Lint/DuplicateMatchPattern:
  Enabled: true
Style/DataInheritance:
  Enabled: true
Style/ExactRegexpMatch:
  Enabled: true
Style/RedundantArrayConstructor:
  Enabled: true
Style/RedundantFilterChain:
  Enabled: true
Style/RedundantLineContinuation:
  Enabled: true
Style/RedundantRegexpConstructor:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true
Lint/UselessRescue:
  Enabled: true
Metrics/CollectionLiteralLength:
  Enabled: true
Style/ArrayIntersect:
  Enabled: true
Style/ComparableClamp:
  Enabled: true
Style/ConcatArrayLiterals:
  Enabled: true
Style/DirEmpty:
  Enabled: true
Style/FileEmpty:
  Enabled: true
Style/MapToSet:
  Enabled: true
Style/MinMaxComparison:
  Enabled: true
Style/RedundantConstantBase:
  Enabled: true
Style/RedundantDoubleSplatHashBraces:
  Enabled: true
Style/RedundantHeredocDelimiterQuotes:
  Enabled: true
